Command: add (first draft)

diff --git a/dws b/dws
--- a/dws
+++ b/dws
@@ -158,8 +158,11 @@ function init() {
 
 
 function add_or_sync() {
-    echo "Don't know how to do nothing!"
-    exit 42
+    if [ -f .dws ]; then
+        sync
+    else
+        add
+    fi
 }
 
 
@@ -169,9 +172,59 @@ function list() {
 }
 
 
+function die_add() {
+    cat 1>&2 <<USAGE
+Usage: $0 add [nickname]
+       $0 -h
+
+Adds a work directory to the workspace under a chosen nickname. By default,
+the nickname corresponds to the directory's own name. $0 will help you choose
+a unique name. A work directory can be added only under a single nickname.
+
+After the work directory has been added to the workspace, it is synchronized
+for the first time.
+
+Options:
+
+    -h  Print out this help.
+USAGE
+    exit $1
+}
+
+
 function add() {
-    echo "Don't know how to add!"
-    exit 42
+    if [ -f ".dws" ]; then
+        echo "Directory already added as $(cat .dws) on this workstation."
+        exit 2
+    fi
+
+    init
+
+    while getopts 'h' arg; do
+        case "$arg" in
+            h) die_add 0 ;;
+            *) die_add 1 ;;
+        esac
+    done
+    shift $((OPTIND - 1))
+
+    name_dir="$1"
+    test -z "$name_dir" && name_dir="$(basename "$(pwd)")"
+    while true; do
+        if [ -z "$name_dir" ]; then
+            echo "You can't use an empty string to nickname a work directory. Let's try again." 1>&2
+        elif echo "$name_dir" | egrep -qv '[a-zA-Z0-9_.][-a-zA-Z0-9_.]*'; then
+            echo "Nickname this work directory using only letters, numbers, dashes, underscores and periods. The nickname $name_dir does not work." 1>&2
+        elif is_name_dir_used "$name_dir"; then
+            echo "Work directory nickname $name_dir is already being used on this workstation. Let's try again." 1>&2
+        else
+            echo "$name_dir" >.dws
+            break
+        fi
+        read -ep "Input nickname: "
+        name_dir="$(echo "$REPLY" | xargs)"
+    done
+    sync
 }
 
 
